project:
  type: website
  output-dir: docs

website:
  title: "Carla Quintanilla"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Drawing"
        href: Drawing.qmd
      - text: "Resume"
        href: resume.qmd
  page-footer:
    background: light
    left: Copyright 2025, Carla Quintanilla
    right: Hola!

format:
  html:
    theme:
      - cosmos
      - brand
    css: styles.css
    toc: true

editor: visual

